name: netket_env

channels:
  - numba
  - defaults
  - conda-forge

dependencies:
  - python>=3.8
  - numpy>=1.20
  - scipy>=1.5.2
  - networkx
  - mpi4jax
  - tqdm
  - pip
  - matplotlib
  - openmpi
  - mpi4py
  - mkl
  - numba
