// Copyright 2018 The Simons Foundation, Inc. - All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef NETKET_SUPERVISED_CC
#define NETKET_SUPERVISED_CC

namespace netket {

class Supervised {
 public:
  explicit Supervised(const json &supervisedPars) {
    // Relevant parameters for supervised learning
    // is stored in supervisedPars.
    CheckFieldExists(supervisedPars, "Supervised");
    const std::string loss_name =
        FieldVal(supervisedPars["Supervised"], "Loss", "Supervised");

    if (loss_name == "Overlap") {
      // Input data is encoded in Json file with name "InputFilename".
      auto data_json = ReadJsonFromFile(supervisedPars["Supervised"]["InputFilename"]);
      using DataType = Data<double>;
      DataType data(data_json, supervisedPars);

      // Make a machine using the Hilbert space extracted from
      // the data.
      using MachineType = Machine<std::complex<double>>;
      MachineType machine(data.GetHilbert(), supervisedPars);

      // Now need Optimizer to optimize overlap, using batches generated by Data

    } else {
      std::stringstream s;
      s << "Unknown Supervised loss: " << loss_name;
      throw InvalidInputError(s.str());
    }
  }
};

}  // namespace netket

#endif
