import numpy as np

from netket.hilbert import Spin, SpinOrbitalFermions
from netket.utils.group import Permutation, cyclic_group

from netket._src.operator.permutation.fermion import PermutationOperatorFermion
from netket._src.operator.permutation.spin import PermutationOperator
from netket._src.operator.spin_flip import SpinFlipOperator
from netket._src.symmetry.labeled_representation import LabeledRepresentation


def _identity_permutation(size: int) -> Permutation:
    return Permutation(
        permutation_array=np.arange(size),
        name="Identity()",
        validate=False,
    )


def spin_flip_representation(
    hilbert: Spin | SpinOrbitalFermions,
) -> LabeledRepresentation:
    r"""
    Construct the :math:`\mathbb{Z}_2` representation generated by spin flip.

    On a :class:`~netket.hilbert.Spin` Hilbert space, the non-trivial element acts as
    :math:`|m_1, \ldots, m_N\rangle \mapsto |-m_1, \ldots, -m_N\rangle`.

    On a :class:`~netket.hilbert.SpinOrbitalFermions` Hilbert space, the non-trivial
    element swaps spin subsectors according to :math:`m_s \mapsto -m_s`, leaving the
    orbital index unchanged.

    Args:
        hilbert: A spin or spinful fermionic Hilbert space.

    Returns:
        An :class:`~netket.symmetry.LabeledRepresentation` of :math:`\mathbb{Z}_2`
        with irrep labels ``['+1', '-1']`` (even/symmetric and odd/antisymmetric
        sectors respectively).

    Raises:
        TypeError: If `hilbert` is not supported.
        ValueError: If spin flip does not preserve the Hilbert space constraints.
    """

    group = cyclic_group(2)
    identity_element, flip_element = group.elems

    identity_cls = (
        PermutationOperatorFermion
        if isinstance(hilbert, SpinOrbitalFermions)
        else PermutationOperator
    )

    return LabeledRepresentation(
        group,
        {
            identity_element: identity_cls(
                hilbert, _identity_permutation(hilbert.size)
            ),
            flip_element: SpinFlipOperator(hilbert),
        },
    )
