name: Coverage

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-latest, macos-latest]
    env:
       MPICH_INTERFACE_HOSTNAME: localhost
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install MPI
        run: |
          sh ./conf/travis-install-mpi.sh mpich

      - name: Pip install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest numpy coverage jax jaxlib mpi4py mpi4jax networkx python-igraph jax jaxlib mpi4jax
          if [ -f requirements.txt ]; then 
            pip install -r requirements.txt
          fi
          pip install -v -e .

      - name: MPI tests
        run: |
          mpirun -host localhost:2 -v -np 2 coverage run -m pytest --dirations=0 --verbose Test/MPI

      - name: Netket tests
        run : coverage run

      - name: Combine multiple coverage results
        run: |
          coverage combine
          
      - name: Upload coverage
        uses: codecov/codecov-action@v1
