name: "Pull Request Docs"
on: 
- pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: mdecoleman/pr-branch-name@1.0.0
      id: vars
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - run: echo ${{ steps.vars.outputs.branch }}

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Pip install python dependencies
      run: |
        pip install -e ".[dev,mpi]"

    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"

    # Create an artifact of the html output.
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: docs/_build/html/

    # Publish built docs to gh-pages branch.
    # ===============================
    - name: Commit documentation changes
      run: |
        git clone https://github.com/netket/netket.git --branch gh-pages --single-branch gh-pages
        rm -rf gh-pages/${{ steps.vars.outputs.branch }}
        mkdir -p gh-pages/${{ steps.vars.outputs.branch }}
        cp -r docs/_build/html/* gh-pages/${{ steps.vars.outputs.branch }}/
        cd gh-pages/${{ steps.vars.outputs.branch }}
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation for PR ${{ steps.vars.outputs.branch }}" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
