name: "Website/Docs"

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    # Determine the branch name
    - uses: mdecoleman/pr-branch-name@1.0.0
      id: determine-branch
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    # Print the branch namee
    - run: echo ${{ steps.determine-branch.outputs.branch }}

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Pip install python dependencies
      run: |
        pip install -e ".[dev]"

    - name: Install docs dependencies and Pandoc
      run: |
        sudo apt-get -y install pandoc
        pip install -r docs/requirements.txt

    - name: Make docs
      run: |
        cd docs 
        make html

    # Create an artifact of the html output.
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: docs/_build/html/

    # Publish built docs to gh-pages branch.
    # https://github.com/peaceiris/actions-gh-pages
    - name: Deploy Website and Docs
      if: success() && github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html/

    - name: Deploy Website and Docs Preview
      if: success() && github.ref != 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html/
        destination_dir: preview/${{ steps.determine-branch.outputs.branch }}
